version: '3.8'

services:
  springboot-app:
    image: openjdk:17
    container_name: springboot-app
    working_dir: /app
    volumes:
      - .:/app
    command: ["java", "-jar", "target/nginx_http-0.0.1-SNAPSHOT.jar"]
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - springboot-app
